title: Our Date Blog
description: Memories from our adventures together
url: https://minininja-swag.github.io/date-blog
theme: minima

collections:
  dates:
    output: true
    permalink: /dates/:title/

defaults:
  - scope: { path: "", type: dates }
    values:
      layout: date

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 6
paginate_path: "/page:num"

# Build search index
exclude: [admin, node_modules, README.md]
