backend:
  name: github
  repo: minininja-swag/date-blog
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "dates"
    label: "Dates"
    folder: "_dates"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "location", label: "Location", required: false }
      - { name: "coords", label: "Coords [lat,lon]", widget: "list", allow_add: false, required: false, field: { name: "coord", label: "Coord", widget: "number" } }
      - { name: "tags", label: "Tags", widget: "list", required: false }
      - { name: "rating", label: "Rating (1-5)", widget: "number", min: 1, max: 5, required: false }
      - { name: "summary", label: "Summary", widget: "text", required: false }
      - { name: "photos", label: "Photos", widget: "list", field: { name:"image", label:"Image", widget:"image" }, required: false }
      - { name: "body", label: "Body", widget: "markdown" }
